on:
  workflow_call:

env:
  env: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Set up SSH Tunnel
        run: |
          ssh -f -N -L 3306:${{ secrets.DB_HOST }}:3306 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      - name: Run migrations
        run: |
          echo "Running migrations"
          npx sequelize-cli db:migrate --url "mariadb://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@localhost:3306/${{ secrets.DB_DATABASE }}"
        env:
          NODE_ENV: ${{ env.env }}
