name: Git Flow Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check branch name
        run: |
          echo "Source Branch : ${{github.event.pull_request.head.ref}}"
          regex="(issue|ISSUE)-([a-z0-9]+)$"
          if [[ ${{github.event.pull_request.head.ref}} =~ $regex ]]; then
            echo "✅ Branch name is correct : ${{github.event.pull_request.head.ref}}"
          else
            echo "❌ The branch name does not respect the regex rule."
            echo "It should look like: issue-123 or ISSUE-123"
            exit 1
          fi
